[package]
name = "rpg"
version = "0.1.0"
authors = ["Naoki Numaguchi <naoki.numaguchi@groove-x.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5"
bevy_tilemap = "0.4"
bevy_egui = "0.5"
rand = "0.7.3"
